name: tennisAI
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - appnope=0.1.4=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.6.15=hbd8a1cb_0
  - comm=0.2.2=pyhd8ed1ab_1
  - debugpy=1.8.11=py310h313beb8_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - expat=2.7.1=h313beb8_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=6.29.5=pyh57ce528_0
  - ipython=8.37.0=pyh8f84b5b_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - krb5=1.21.3=h237132a_0
  - libcxx=17.0.6=he5c5206_4
  - libedit=3.1.20191231=hc8eb9b7_2
  - libffi=3.4.4=hca03da5_1
  - libsodium=1.0.20=h99b78c6_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - ncurses=6.4=h313beb8_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.5.1=h81ee809_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.4=pyhd8ed1ab_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.1=pyhc872135_2
  - platformdirs=4.3.8=pyhe01879c_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - psutil=5.9.0=py310h80987f9_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.10.18=h19e8193_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - pyzmq=26.2.0=py310h313beb8_0
  - readline=8.2=h1a28f6b_0
  - setuptools=78.1.1=py310hca03da5_0
  - six=1.17.0=pyhd8ed1ab_0
  - sqlite=3.45.3=h80987f9_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.14=h6ba3021_1
  - tornado=6.5.1=py310h80987f9_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.14.0=pyhe01879c_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=py310hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zeromq=4.3.5=h9f5b81c_6
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.2.13=h18a0788_1
  - pip:
      - absl-py==2.3.0
      - appdirs==1.4.4
      - astunparse==1.6.3
      - attrs==25.3.0
      - beautifulsoup4==4.13.4
      - bs4==0.0.2
      - certifi==2025.6.15
      - charset-normalizer==3.4.2
      - contourpy==1.3.2
      - cssselect==1.3.0
      - cycler==0.12.1
      - et-xmlfile==2.0.0
      - fake-useragent==2.2.0
      - flatbuffers==25.2.10
      - fonttools==4.58.4
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.73.1
      - h11==0.16.0
      - h5py==3.14.0
      - idna==3.10
      - joblib==1.5.1
      - keras==3.10.0
      - kiwisolver==1.4.8
      - libclang==18.1.1
      - lxml==6.0.0
      - lxml-html-clean==0.4.2
      - markdown==3.8.2
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.3
      - mdurl==0.1.2
      - ml-dtypes==0.5.1
      - namex==0.1.0
      - numpy==2.1.3
      - openpyxl==3.1.5
      - opt-einsum==3.4.0
      - optree==0.16.0
      - outcome==1.3.0.post0
      - pandas==2.3.0
      - parse==1.20.2
      - pillow==11.3.0
      - protobuf==5.29.5
      - pycryptodome==3.23.0
      - pyee==11.1.1
      - pyparsing==3.2.3
      - pyppeteer==2.0.0
      - pyquery==2.0.1
      - pysocks==1.7.1
      - python-dotenv==1.1.1
      - python-graphviz==0.21
      - pytz==2025.2
      - requests==2.32.4
      - requests-html==0.10.0
      - rich==14.0.0
      - scikit-learn==1.7.0
      - scipy==1.15.3
      - selenium==4.34.1
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soupsieve==2.7
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.19.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==3.1.0
      - threadpoolctl==3.6.0
      - tqdm==4.67.1
      - trio==0.30.0
      - trio-websocket==0.12.2
      - tzdata==2025.2
      - urllib3==1.26.20
      - w3lib==2.3.1
      - webdriver-manager==4.0.2
      - websocket-client==1.8.0
      - websockets==10.4
      - werkzeug==3.1.3
      - wrapt==1.17.2
      - wsproto==1.2.0
      - xgboost==3.0.2
